
import { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  {
    id: 'push-up',
    name: 'Push-ups',
    description: 'Target chest, shoulders, and triceps.',
    instructions: '1. High plank position. \n2. Lower chest to floor. \n3. Push back up.',
    difficulty: 'Intermediate',
    duration: 10,
    calories: 100,
    image: 'https://images.pexels.com/photos/416405/pexels-photo-416405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'],
    angleThresholds: { up: 160, down: 85 },
    cameraFacing: 'side',
    metValue: 8.0,
    category: 'Upper body',
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-ups',
    description: 'Tricep focused variation.',
    instructions: 'Hands close together forming a diamond. Lower chest and push.',
    difficulty: 'Advanced',
    duration: 12,
    calories: 110,
    image: 'https://images.pexels.com/photos/176782/pexels-photo-176782.jpeg?auto=compress&cs=tinysrgb&w=1260',
    angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'],
    angleThresholds: { up: 155, down: 80 },
    cameraFacing: 'side',
    metValue: 9.0,
    category: 'Upper body',
  },
  {
    id: 'squat',
    name: 'Squats',
    description: 'The king of lower body exercises.',
    instructions: '1. Feet shoulder-width apart. \n2. Lower hips until thighs are parallel to floor. \n3. Drive through heels.',
    difficulty: 'Beginner',
    duration: 10,
    calories: 80,
    image: 'https://images.pexels.com/photos/791763/pexels-photo-791763.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'],
    angleThresholds: { up: 165, down: 95 },
    cameraFacing: 'side',
    metValue: 5.5,
    category: 'Lower body',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridges',
    description: 'Target glutes and hamstrings.',
    instructions: 'Lie on back, knees bent. Lift hips toward ceiling.',
    difficulty: 'Beginner',
    duration: 8,
    calories: 60,
    image: 'https://images.pexels.com/photos/6456294/pexels-photo-6456294.jpeg?auto=compress&cs=tinysrgb&w=1260',
    angleLandmarks: ['leftShoulder', 'leftHip', 'leftKnee'],
    angleThresholds: { up: 170, down: 130 },
    cameraFacing: 'side',
    metValue: 4.0,
    category: 'Lower body',
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curls',
    description: 'Sculpt your arms.',
    instructions: '1. Palms forward. \n2. Curl weights to shoulders. \n3. Controlled lowering.',
    difficulty: 'Beginner',
    duration: 10,
    calories: 60,
    image: 'https://images.pexels.com/photos/1431283/pexels-photo-1431283.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'],
    angleThresholds: { up: 155, down: 55 }, 
    cameraFacing: 'side',
    metValue: 3.5,
    category: 'Upper body',
  },
  { 
    id: 'lunges', 
    name: 'Lunges', 
    description: 'Build unilateral leg strength.', 
    instructions: 'Step forward and drop back knee towards the floor.', 
    difficulty: 'Beginner', 
    duration: 10, 
    calories: 90, 
    image: 'https://images.pexels.com/photos/6456303/pexels-photo-6456303.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], 
    angleThresholds: { up: 160, down: 100 }, 
    cameraFacing: 'side',
    metValue: 5.0,
    category: 'Lower body',
  },
  { 
    id: 'crunches', 
    name: 'Crunches', 
    description: 'Core stability and strength.', 
    instructions: 'Lying on back, lift shoulders using abs only.', 
    difficulty: 'Beginner', 
    duration: 5, 
    calories: 40, 
    image: 'https://images.pexels.com/photos/3764395/pexels-photo-3764395.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    angleLandmarks: ['leftShoulder', 'leftHip', 'leftKnee'], 
    angleThresholds: { up: 140, down: 110 },
    cameraFacing: 'side',
    metValue: 4.0,
    category: 'Upper body',
  },
  { 
    id: 'jumping-jacks', 
    name: 'Jumping Jacks', 
    description: 'Total body cardio blast.', 
    instructions: 'Jump out while arms swing overhead. Return to center.', 
    difficulty: 'Beginner', 
    duration: 10, 
    calories: 100, 
    image: 'https://images.pexels.com/photos/7031705/pexels-photo-7031705.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    angleLandmarks: ['leftHip', 'leftShoulder', 'leftElbow'],
    angleThresholds: { up: 155, down: 35 },
    cameraFacing: 'front',
    metValue: 8.0,
    category: 'Cardio',
    type: 'reps'
  },
  { 
    id: 'mountain-climbers', 
    name: 'Mountain Climbers', 
    description: 'High intensity core cardio.', 
    instructions: 'In plank position, drive knees to chest rapidly.', 
    difficulty: 'Intermediate', 
    duration: 8, 
    calories: 120, 
    image: 'https://images.pexels.com/photos/6456294/pexels-photo-6456294.jpeg?auto=compress&cs=tinysrgb&w=1260', 
    angleLandmarks: ['leftShoulder', 'leftHip', 'leftKnee'],
    angleThresholds: { up: 160, down: 110 },
    cameraFacing: 'side',
    metValue: 10.0,
    category: 'Cardio',
    type: 'reps'
  },
  { 
    id: 'burpees', 
    name: 'Burpees', 
    description: 'Full body metabolic finisher.', 
    instructions: 'Drop to plank, push up, jump back in, jump up.', 
    difficulty: 'Advanced', 
    duration: 15, 
    calories: 150, 
    image: 'https://images.pexels.com/photos/3763704/pexels-photo-3763704.jpeg?auto=compress&cs=tinysrgb&w=1260', 
    angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'],
    angleThresholds: { up: 170, down: 100 },
    cameraFacing: 'side',
    metValue: 12.0,
    category: 'Cardio',
    type: 'reps'
  },
  { 
    id: 'plank', 
    name: 'Plank', 
    description: 'Ultimate core hold.', 
    instructions: 'Hold a straight line from head to heels.', 
    difficulty: 'Beginner', 
    duration: 1, 
    calories: 10, 
    image: 'https://images.pexels.com/photos/3112004/pexels-photo-3112004.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 
    metValue: 2.5,
    category: 'Upper body',
    angleLandmarks: ['leftShoulder', 'leftHip', 'leftKnee'],
    angleThresholds: { up: 165, down: 160 },
    holdPhase: 'up',
    cameraFacing: 'side'
  },
];

const findEx = (id: string) => EXERCISES.find(e => e.id === id)!;

export const PLAN_WORKOUTS: Exercise[] = [
    {
        id: 'lower-body-plan',
        name: 'Lower Body Power',
        description: "6 Targeted movements for lower body strength",
        instructions: "A full circuit focusing on power, stability, and growth.",
        difficulty: 'Intermediate',
        duration: 30,
        calories: 280,
        image: 'https://images.pexels.com/photos/1552252/pexels-photo-1552252.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        category: 'Lower body',
        metValue: 6.5,
        subExercises: [
            { ...findEx('squat'), type: 'reps', sets: 3, reps: 15 },
            { ...findEx('lunges'), type: 'reps', sets: 3, reps: 12 },
            { ...findEx('glute-bridge'), type: 'reps', sets: 3, reps: 20 },
            { id: 'side-lunges', name: 'Side Lunges', description: 'Lateral leg strength.', instructions: 'Step to side and lower hips.', difficulty: 'Intermediate', duration: 5, calories: 40, image: 'https://images.pexels.com/photos/6456303/pexels-photo-6456303.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'reps', sets: 3, reps: 10, metValue: 5.0, angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], angleThresholds: { up: 160, down: 100 }, cameraFacing: 'front' },
            { id: 'calf-raises', name: 'Calf Raises', description: 'Strengthen ankles and calves.', instructions: 'Rise on toes and lower slowly.', difficulty: 'Beginner', duration: 4, calories: 30, image: 'https://images.pexels.com/photos/791763/pexels-photo-791763.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'reps', sets: 3, reps: 20, metValue: 3.5, angleLandmarks: ['leftKnee', 'leftAnkle', 'leftWrist'], angleThresholds: { up: 150, down: 130 }, cameraFacing: 'side' },
            { id: 'wall-sits', name: 'Wall Sit Hold', description: 'Isometric leg burn.', instructions: 'Sit against wall, knees 90 deg.', difficulty: 'Intermediate', duration: 3, calories: 20, image: 'https://images.pexels.com/photos/3112004/pexels-photo-3112004.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'time', sets: 3, holdTime: 45, metValue: 3.8, angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], angleThresholds: { up: 110, down: 85 }, holdPhase: 'down', cameraFacing: 'side' }
        ]
    },
    {
        id: 'upper-body-plan',
        name: 'Upper Body Strength',
        description: "6 Core exercises for chest, back and arms",
        instructions: "Balanced upper body pushing and stability circuit.",
        difficulty: 'Intermediate',
        duration: 35,
        calories: 310,
        image: 'https://images.pexels.com/photos/3289711/pexels-photo-3289711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        category: 'Upper body',
        metValue: 5.8,
        subExercises: [
            { ...findEx('push-up'), type: 'reps', sets: 3, reps: 12 },
            { ...findEx('bicep-curl'), type: 'reps', sets: 3, reps: 15 },
            { ...findEx('diamond-push-up'), type: 'reps', sets: 3, reps: 10 },
            { ...findEx('crunches'), type: 'reps', sets: 3, reps: 20 },
            { id: 'shoulder-taps', name: 'Shoulder Taps', description: 'Plank stability.', instructions: 'In plank, tap opposite shoulder.', difficulty: 'Intermediate', duration: 6, calories: 50, image: 'https://images.pexels.com/photos/176782/pexels-photo-176782.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'reps', sets: 3, reps: 20, metValue: 4.5, angleLandmarks: ['leftShoulder', 'leftElbow', 'leftWrist'], angleThresholds: { up: 170, down: 160 }, cameraFacing: 'front' },
            { ...findEx('plank'), type: 'time', sets: 3, holdTime: 60 },
        ]
    },
    {
        id: 'cardio-plan',
        name: 'HIIT Cardio Burn',
        description: "6 High-intensity cardio blasts",
        instructions: "Keep the heart rate high and rest short.",
        difficulty: 'Advanced',
        duration: 25,
        calories: 400,
        image: 'https://images.pexels.com/photos/863977/pexels-photo-863977.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        category: 'Cardio',
        metValue: 10.5,
        subExercises: [
            { ...findEx('jumping-jacks'), type: 'reps', sets: 3, reps: 50 },
            { ...findEx('high-knees'), name: 'High Knees', description: 'Rapid sprint in place.', instructions: 'Knees to hip level.', difficulty: 'Intermediate', duration: 5, calories: 60, image: 'https://images.pexels.com/photos/7031706/pexels-photo-7031706.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'reps', sets: 3, reps: 40, metValue: 9.0, angleLandmarks: ['leftShoulder', 'leftHip', 'leftKnee'], angleThresholds: { up: 160, down: 100 }, cameraFacing: 'side' },
            { ...findEx('mountain-climbers'), type: 'reps', sets: 3, reps: 30 },
            { ...findEx('burpees'), type: 'reps', sets: 3, reps: 10 },
            { id: 'skater-jumps', name: 'Skater Jumps', description: 'Lateral agility.', instructions: 'Jump side to side like a skater.', difficulty: 'Intermediate', duration: 6, calories: 70, image: 'https://images.pexels.com/photos/863977/pexels-photo-863977.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'reps', sets: 3, reps: 20, metValue: 8.5, angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], angleThresholds: { up: 160, down: 120 }, cameraFacing: 'front' },
            { id: 'butt-kicks', name: 'Butt Kicks', description: 'Fast leg turnover.', instructions: 'Run in place kicking heels to glutes.', difficulty: 'Beginner', duration: 4, calories: 40, image: 'https://images.pexels.com/photos/7031706/pexels-photo-7031706.jpeg?auto=compress&cs=tinysrgb&w=1260', type: 'reps', sets: 3, reps: 40, metValue: 7.0, angleLandmarks: ['leftHip', 'leftKnee', 'leftAnkle'], angleThresholds: { up: 120, down: 45 }, cameraFacing: 'side' }
        ]
    }
];
